apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  POSTGRES_DB: postgres
  KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC: customers
  SPARK_MASTER_URL: spark://spark-master:7077
  CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123
  CLICKHOUSE_USER: default
  CLICKHOUSE_PASSWORD: ""
