apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  postgres-user: bXl1c2Vy
  postgres-password: bXlwYXNzd29yZA==
  clickhouse-password: Y2xpcmtob3VzZXI=  # Base64 закодированный пароль для ClickHouse
